[book]
authors = ["Kevin Amado"]
language = "en"
multilingual = false
src = "src"
title = "Open Source Tutorial"

[output.html]
default-theme = "light"
edit-url-template = "https://github.com/<owner>/<repo>/edit/master/{path}"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Tech-Start-UCalgary/tsu-resources"
git-repository-icon = "fa-github"
site-url = "/open-source-tutorial/"
