[book]
authors = ["Kevin Amado"]
language = "en"
multilingual = false
src = "src"
title = "Open Sourcing Like A Pro"

[output.html]
default-theme = "light"
edit-url-template = "https://github.com/Tech-Start-UCalgary/tsu-resources/edit/master/open-sourcing-like-a-pro/{path}"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/Tech-Start-UCalgary/tsu-resources"
git-repository-icon = "fa-github"
site-url = "/open-sourcing-like-a-pro/"

[output.html.fold]
enable = true
level = 0
