name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: git-clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install-nix
        uses: cachix/install-nix-action@v15

      - name: build
        run: nix build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: docs.techstartucalgary.com
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs
          publish_dir: result/html
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
